# Generated by Django 3.1.1 on 2020-10-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fix_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('class_id', models.CharField(max_length=20)),
                ('msg', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='newsinfo',
        ),
    ]
