# Generated by Django 3.1.1 on 2020-10-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixapp', '0002_auto_20201027_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='fix_class',
            name='is_deleta',
            field=models.BooleanField(default=0),
        ),
    ]
