# Generated by Django 3.1.1 on 2020-10-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixapp', '0007_auto_20201027_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_fix',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
