# Generated by Django 3.1.1 on 2020-10-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixapp', '0008_auto_20201027_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_fix',
            name='class_id',
            field=models.CharField(max_length=20, verbose_name='待维修班级'),
        ),
        migrations.AlterField(
            model_name='class_fix',
            name='email',
            field=models.CharField(max_length=30, verbose_name='联系邮箱'),
        ),
        migrations.AlterField(
            model_name='class_fix',
            name='flag',
            field=models.BooleanField(choices=[(0, '待维修'), (1, '已维修')], verbose_name='维修状态'),
        ),
        migrations.AlterField(
            model_name='class_fix',
            name='msg',
            field=models.TextField(verbose_name='待维修事项'),
        ),
        migrations.AlterField(
            model_name='class_fix',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='class_fix',
            name='stu_id',
            field=models.CharField(max_length=20, verbose_name='学生学号'),
        ),
        migrations.AlterField(
            model_name='class_fix',
            name='stu_name',
            field=models.CharField(max_length=20, verbose_name='报修人'),
        ),
        migrations.AlterField(
            model_name='class_fix',
            name='time',
            field=models.CharField(max_length=50, verbose_name='报修时间'),
        ),
    ]
