# Generated by Django 3.1.1 on 2020-10-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixapp', '0009_auto_20201027_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_fix',
            name='flag',
            field=models.CharField(max_length=20, verbose_name='维修状态'),
        ),
    ]
