# Generated by Django 3.1.1 on 2020-10-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixapp', '0010_auto_20201027_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_fix',
            name='flag',
            field=models.BooleanField(choices=[(0, '未维修'), (1, '已维修')], verbose_name='维修状态'),
        ),
    ]
