# Generated by Django 3.1.1 on 2020-10-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixapp', '0012_class_fix_text_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_fix',
            name='text_flag',
            field=models.CharField(default='', max_length=20),
        ),
    ]
