# Generated by Django 3.1.1 on 2020-10-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixapp', '0013_auto_20201028_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_fix',
            name='text_flag',
            field=models.CharField(default='------', max_length=20),
        ),
    ]
