# Generated by Django 3.1.1 on 2020-10-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixapp', '0014_auto_20201028_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_fix',
            name='text_flag',
        ),
        migrations.AlterField(
            model_name='class_fix',
            name='flag',
            field=models.CharField(default='未维修', max_length=20, verbose_name='维修状态'),
        ),
    ]
