# Generated by Django 3.1.1 on 2020-10-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixapp', '0016_class_fix_f_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_fix',
            name='f_flag',
        ),
        migrations.AlterField(
            model_name='class_fix',
            name='flag',
            field=models.BooleanField(choices=[(1, '已维修'), (0, '未维修')], verbose_name='维修状态'),
        ),
    ]
