# Generated by Django 3.1.1 on 2020-10-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixapp', '0017_auto_20201029_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='user1.jpg', upload_to='ptotos')),
            ],
        ),
    ]
