# Generated by Django 3.1.1 on 2020-10-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixapp', '0019_auto_20201029_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_fix',
            name='photo',
            field=models.ImageField(default='0.jpg', upload_to='photo', verbose_name='现场照片'),
        ),
    ]
